version: "2"
services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./registry:/var/lib/registry
  app:
    image: jc21/registry-ui
    ports:
      - 80:80
    environment:
      - REGISTRY_HOST=104.248.38.167:5000
      - REGISTRY_SSL=false
      - REGISTRY_DOMAIN=104.248.38.167:5000
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_HTTP_SECRET=YOUR_SECRETE_HERE
    restart: on-failure
    depends_on:
      - registry
